name: Deploy to GitHub Packages

on:
  push:
    tags:
      - '*'
      

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install and publish
        run: |
          yarn install
          yarn publish --access public
        working-directory: packages/excalidraw
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}