name: Publish to GitHub Packages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: corepack enable
      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarn run build

      - name: Publish to GitHub Packages
        run: yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
